### ISSUE TITLE
Demo on predix-ui.com not working

### ISSUE THREAD

**Issue by Asheq** [predixdesignsystem/px-vis-paired-bar#1]
Just an FYI: https://www.predix-ui.com/#/elements/vis/px-vis-paired-bar

**Comment by jimdefrisco** [comment]
Thanks for the heads up.

**Comment by arongraham-ge** [comment]
Path to demo data was in error. Fixed in commit 68c0d2fa5eec0587cf6f064552884bb22c64b5e0

**Comment by arongraham-ge** [comment]
Path to demo data was in error. Fixed in commit 68c0d2fa5eec0587cf6f064552884bb22c64b5e0
